students: [
	{
		firstName: "Aleksandr",
		midleName: "Vladimirovich",
		lastname: "Tugolukov",
		numberGroup: "222",
		gender: "мужской",
		date: "2005-02-10",
		status: false,
		filter: true,
		id: 1,
	},
	{
		firstName: "Vasya",
		midleName: "Gennadievich",
		lastname: "Ivanov",
		numberGroup: "111",
		gender: "мужской",
		date: "2001-05-10",
		status: false,
		filter: true,
		id: 2,
	},
	{
		firstName: "Oksana",
		midleName: "Viktorovna",
		lastname: "Sinicina",
		numberGroup: "333",
		gender: "женский",
		date: "1995-06-21",
		status: false,
		filter: true,
		id: 3,
	},
	{
		firstName: "Nikita",
		midleName: "Sergeevich",
		lastname: "Minin",
		numberGroup: "5555",
		gender: "мужской",
		date: "2020-06-10",
		status: false,
		filter: true,
		id: 4,
	},
	{
		firstName: "Nikita",
		midleName: "Sergeevich",
		lastname: "Minin",
		numberGroup: "444",
		gender: "мужской",
		date: "2020-06-10",
		status: false,
		filter: true,
		id: 5,
	},
	{
		firstName: "Nikita",
		midleName: "Sergeevich",
		lastname: "Minin",
		numberGroup: "111",
		gender: "мужской",
		date: "2020-06-10",
		status: false,
		filter: true,
		id: 6,
	},
	{
		firstName: "Nikita",
		midleName: "Sergeevich",
		lastname: "Hakabv",
		numberGroup: "111",
		gender: "мужской",
		date: "2020-06-10",
		status: false,
		filter: true,
		id: 7,
	},
	{
		firstName: "Nikita",
		midleName: "SergMihach",
		lastname: "Minin",
		numberGroup: "777",
		gender: "мужской",
		date: "2020-06-10",
		status: false,
		filter: true,
		id: 8,
	},
	{
		firstName: "Nikita",
		midleName: "Sergeevich",
		lastname: "Minin",
		numberGroup: "555",
		gender: "мужской",
		date: "2020-06-10",
		status: false,
		filter: true,
		id: 9,
	},
	{
		firstName: "Sveta",
		midleName: "Sergeevich",
		lastname: "Minin",
		numberGroup: "222",
		gender: "мужской",
		date: "2020-06-10",
		status: false,
		filter: true,
		id: 10,
	},
];
